support tensorflow v2.x
alibaba/graph-learn pull request #132
Opened 2020-12-10 15:08 UTC by acezen

2020-12-10 15:09 UTC, acezen commented
cc/ @sighingnow

2020-12-11 02:32 UTC, sighingnow requested changes

2020-12-11 02:32 UTC, sighingnow commented on examples/tf/bipartite_graphsage/train_unsupervised.py
> +itry:
`itry` -> `try`.

2020-12-11 02:38 UTC, acezen commented
cc/ @jackonan please take a review, thanks

2020-12-11 03:39 UTC, baoleai approved these changes

2020-12-11 03:40 UTC, baoleai approved these changes

2020-12-11 05:11 UTC, sighingnow commented
Closed as merged into master.

2020-12-11 05:11 UTC, closed without merging